import Head from "next/head";
import Banner from "../components/Home/Banner";
import ChooseUs from "../components/Home/ChooseUs";
import ContactBanner from "../components/Home/ContactBanner";
import Facilities from "../components/Home/Facilities";
import Footer from "../components/Home/Footer";
import Navbar from "../components/Home/Navbar";
import Platform from "../components/Home/Platform";
import Services from "../components/Home/Services";
import SoftDevCycle from "../components/Home/SoftDevCycle";
import Testimonials from "../components/Home/Testimonials";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Software Development Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
        <Banner />
      </header>
      <main>
        <Services />
        <Platform />
        <Facilities />
        <ContactBanner />
        <SoftDevCycle />
        <ChooseUs />
        <Testimonials />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
