import Head from "next/head";
import Banner from "../components/Home/Banner";
import Navbar from "../components/Home/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Software Development Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
        <Banner />
      </header>
      <main></main>

      <footer></footer>
    </div>
  );
}
